### ISSUE TITLE
greetings from thingino!

### ISSUE THREAD

**Issue by gtxaspec** [schneemaier/yacam#17]
Hello @schneemaier! I came across your project while searching for Ingenic on GitHub and wanted to ask if you've tried Thingino. We fully support models like the v2, Pan v1, Pan v2, v3, and more. Perhaps we could collaborate and combine our efforts? Just wanted to reach out and see if you've heard of Thingino yet.  Anyway, glad to have more people working on some ingenic devices!  Have a great day!

**Comment by schneemaier** [comment]
Hello @gtxaspec ! Thanks for reaching out. I already tried Thingino last week, and the firmware is great, much more advanced than mine.

Unfortunatelly I am not a developer. I can hack things together and make improvements. There are several parts of the current yacam project (which is a fork from Openmiko), that I am still trying to understand. My current goal is to get this project to a state where the features I need are working for my specific use case (in my sporadic spaer time, that is why updates are so rare)

Looking at your project I am not sure if I can a real help there as I am not on your level of programing. I could probably get there if I would have the time, which I don't.

**Comment by gtxaspec** [comment]
hey @schneemaier !

thanks so much for your message and for giving Thingino a try! I’m really glad to hear you liked the firmware. 😊

it sounds like you’re doing some awesome work with the yacam project—even if it’s just in your spare time, every bit of progress counts. Don’t worry about not being a developer; hacking things together and making improvements is how a lot of great developments start!

if you ever have questions or need any help with your project, or if you think there’s something I might be able to assist with, don’t hesitate to reach out.  Wishing you all the best with your project, and hope you find some more of that rare spare time!

take care!
